# Generated by Django 5.1.4 on 2025-01-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='contact_list',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='template',
        ),
    ]
