# Generated by Django 5.1.4 on 2025-01-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_emailcampaign_contact_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTracker',
        ),
    ]
